version: '3.4'
services:
  myapp:
    image: myapp
    build:
      context: Quiz-Demo
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229","index.js"]  